import { spawnSync } from 'node:child_process';
import { appendFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const report = dirname(fileURLToPath(import.meta.url));
const root = resolve(report, '../../..');
const [label, tool, ...args] = process.argv.slice(2);
if (!label || !tool) throw new Error('Expected label, executable, and arguments');
const target = resolve(root, 'target/native-quality-closure');
const temporary = resolve(target, 'tmp');
mkdirSync(temporary, { recursive: true });
const env = { ...process.env, RUSTUP_TOOLCHAIN: '1.96.0', RUSTC: 'D:/cache/cargo/toolchains/1.96.0-x86_64-pc-windows-msvc/bin/rustc.exe', CARGO_TARGET_DIR: target, TMP: temporary, TEMP: temporary, WEBLABEL_CARGO_CWD: 'D:/cache/cargo/bin', WEBLABEL_API_BINARY: resolve(target, 'debug/weblabel-api.exe') };
const cargo = tool === 'cargo';
const executable = cargo ? 'D:/cache/cargo/toolchains/1.96.0-x86_64-pc-windows-msvc/bin/cargo.exe' : tool;
const argv = cargo ? [...args.slice(0, 1), '--manifest-path', resolve(root, 'Cargo.toml'), '--target-dir', target, ...args.slice(1)] : args;
const cwd = cargo ? 'D:/cache/cargo/bin' : root;
const result = spawnSync(executable, argv, { cwd, env, encoding: 'utf8', shell: false, maxBuffer: 64 * 1024 * 1024 });
const output = (result.stdout ?? '') + (result.stderr ?? '');
const rustCounts = [...output.matchAll(/test result: (?:ok|FAILED)\. (\d+) passed; (\d+) failed; (\d+) ignored/g)].map(match => ({ passed: Number(match[1]), failed: Number(match[2]), skipped: Number(match[3]) }));
const vitest = output.match(/Tests\s+(\d+) passed/);
const nodeTests = output.match(/# tests (\d+)[\s\S]*?# pass (\d+)[\s\S]*?# fail (\d+)/);
const testCounts = [...rustCounts, ...(vitest ? [{ passed: Number(vitest[1]), failed: 0, skipped: 0 }] : []), ...(nodeTests ? [{ total: Number(nodeTests[1]), passed: Number(nodeTests[2]), failed: Number(nodeTests[3]) }] : [])];
const evidence = { label, executable, argv, cwd, exit_code: result.status, signal: result.signal, error: result.error?.message ?? null, test_counts: testCounts, environment: { RUSTUP_TOOLCHAIN: env.RUSTUP_TOOLCHAIN, RUSTC: env.RUSTC, CARGO_TARGET_DIR: target, TMP: temporary, TEMP: temporary, WEBLABEL_API_BINARY: env.WEBLABEL_API_BINARY, WEBLABEL_CARGO_CWD: env.WEBLABEL_CARGO_CWD } };
appendFileSync(resolve(report, 'commands.jsonl'), JSON.stringify(evidence) + '\n');
appendFileSync(resolve(report, 'tests.log'), `\n## ${label}\n${JSON.stringify(evidence)}\n${output}\n`);
process.stdout.write(output);
console.log(JSON.stringify(evidence));
process.exitCode = result.status ?? 1;
