import { readFile } from 'node:fs/promises';
import { expect, it } from 'vitest';
import { bootstrap_admin_for_test, start_test_app, type ApiClient } from '../support/app';

type Json = Record<string, any>;
const ontology={guidelines_markdown:'T26 review ontology',labels:[{label_id:'label_person',name:'Person',color:'#0099ff',shortcut:null,allowed_geometry_types:['bbox_xyxy'],attributes:[]}]};
function str(value:unknown,key:string):string {const result=(value as Json)?.[key];if(typeof result!=='string'||!result)throw new Error(`${key} missing`);return result;}
async function addUser(admin:ApiClient,baseUrl:string,projectId:string,role:'annotator'|'reviewer'|'viewer') {
 const username=`t26-${role}-${crypto.randomUUID()}`;const password=`${crypto.randomUUID()}-T26-pass`;
 const user=await admin.request<Json>('POST','/api/users',{username,password});expect(user.status).toBe(201);
 const userId=str(user.json,'user_id');expect((await admin.request('POST',`/api/projects/${projectId}/members`,{user_id:userId,role})).status).toBe(200);
 const login=await fetch(new URL('/api/session/login',baseUrl),{method:'POST',headers:{'content-type':'application/json',origin:baseUrl},body:JSON.stringify({username,password})});expect(login.status).toBe(200);
 const cookie=(login.headers.get('set-cookie')??'').split(';',1)[0]!;const csrf=str(await login.json(),'csrf_token');
 return {userId,client:{request:async<T=unknown>(method:string,path:string,body?:unknown)=>{const response=await fetch(new URL(path,baseUrl),{method,headers:{cookie,'x-csrf-token':csrf,origin:baseUrl,'content-type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});let json:unknown=null;try{json=await response.json();}catch{}return {status:response.status,json:json as T,headers:response.headers};},upload:async()=>{throw new Error('not used');}} as ApiClient};
}

it('fences real annotation PUTs and binds review decisions to submitted revisions',async()=>{
 const app=await start_test_app();
 try {
  const admin=await bootstrap_admin_for_test(app);const project=await admin.request<Json>('POST','/api/projects',{name:`T26 ${crypto.randomUUID()}`,description:'workflow acceptance',allow_self_review:false});expect(project.status).toBe(201);const projectId=str(project.json,'project_id');
  const ontologyResponse=await admin.request<Json>('POST',`/api/projects/${projectId}/ontologies`,ontology);expect(ontologyResponse.status).toBe(201);const ontologyId=str(ontologyResponse.json,'ontology_version_id');
  const bytes=new Uint8Array(await readFile(new URL('../fixtures/media/orientation-1.jpg',import.meta.url)));expect((await admin.upload(`/api/projects/${projectId}/assets`,bytes,'t26.jpg',undefined,'image/jpeg')).status).toBe(202);const drained=await admin.request<Json>('POST','/internal/test/jobs/drain',{});expect(drained.status).toBe(200);expect(drained.json.processed).toBe(1);
  const media=await admin.request<Json>('GET',`/api/projects/${projectId}/assets`);const asset=str((media.json as Json).items[0],'asset_revision_id');const head=await admin.request<Json>('GET',`/api/assets/${asset}/annotation?ontology_version_id=${ontologyId}`);const base=str(head.json,'annotation_revision_id');const document=(head.json as Json).document as Json;
  const annotator=await addUser(admin,app.base_url,projectId,'annotator');const reviewer=await addUser(admin,app.base_url,projectId,'reviewer');const task=await admin.request<Json>('POST',`/api/projects/${projectId}/tasks`,{asset_revision_id:asset,ontology_version_id:ontologyId,assignee_id:annotator.userId});expect(task.status).toBe(200);const taskId=str(task.json,'task_id');
  const lease=await annotator.client.request<Json>('POST',`/api/tasks/${taskId}/lease`,{action:'acquire'});expect(lease.status).toBe(200);const oldToken=lease.json.fencing_token as number;expect(lease.json.lease_seconds).toBe(60);expect(lease.json.heartbeat_seconds).toBe(20);
  const newAnnotator=await addUser(admin,app.base_url,projectId,'annotator');const transfer=await admin.request<Json>('POST',`/api/tasks/${taskId}/lease`,{action:'transfer',holder_id:newAnnotator.userId});expect(transfer.status).toBe(200);const activeToken=transfer.json.fencing_token as number;expect(activeToken).toBeGreaterThan(oldToken);
  const acquired=await newAnnotator.client.request<Json>('POST',`/api/tasks/${taskId}/lease`,{action:'acquire'});expect(acquired.status).toBe(200);expect(acquired.json.fencing_token).toBe(activeToken);
  const saveBody=(token:number,completion:string)=>({operation_id:crypto.randomUUID(),base_revision_id:base,document:{...document,completion},lease:{task_id:taskId,fencing_token:token},suggestion_decisions:[]});
  const unprocessed=await newAnnotator.client.request<Json>('POST',`/api/tasks/${taskId}/submit`,{annotation_revision_ids:[base]});expect(unprocessed.status).toBe(422);expect(unprocessed.json.code).toBe('EMPTY_NOT_NEGATIVE');
  const oldFence=await newAnnotator.client.request<Json>('PUT',`/api/assets/${asset}/annotation`,saveBody(oldToken,'confirmed_negative'));expect(oldFence.status).toBe(409);expect(oldFence.json.code).toBe('STALE_FENCING_TOKEN');
  const negative=await newAnnotator.client.request<Json>('PUT',`/api/assets/${asset}/annotation`,saveBody(activeToken,'confirmed_negative'));expect(negative.status).toBe(200);const revision=str(negative.json.revision,'annotation_revision_id');
  const submission=await newAnnotator.client.request<Json>('POST',`/api/tasks/${taskId}/submit`,{annotation_revision_ids:[revision]});expect(submission.status).toBe(200);const reviewId=str(submission.json,'review_id');
  const selfTask=await admin.request<Json>('POST',`/api/projects/${projectId}/tasks`,{asset_revision_id:asset,ontology_version_id:ontologyId,assignee_id:str((await admin.request<Json>('GET','/api/session')).json,'user_id')});expect(selfTask.status).toBe(200);const selfTaskId=str(selfTask.json,'task_id');const selfLease=await admin.request<Json>('POST',`/api/tasks/${selfTaskId}/lease`,{action:'acquire'});expect(selfLease.status).toBe(200);const selfSubmission=await admin.request<Json>('POST',`/api/tasks/${selfTaskId}/submit`,{annotation_revision_ids:[revision]});expect(selfSubmission.status).toBe(200);const selfReviewId=str(selfSubmission.json,'review_id');
  const selfReview=await admin.request<Json>('POST',`/api/reviews/${selfReviewId}/decision`,{decision:'approve',reason:'self check',revision_ids:[revision]});expect(selfReview.status).toBe(403);expect(selfReview.json.code).toBe('SELF_REVIEW_FORBIDDEN');
  const wrongRevision=await reviewer.client.request<Json>('POST',`/api/reviews/${reviewId}/decision`,{decision:'approve',reason:'wrong version',revision_ids:[base]});expect(wrongRevision.status).toBe(409);expect(wrongRevision.json.code).toBe('REVIEW_REVISION_MISMATCH');
  const approval=await reviewer.client.request<Json>('POST',`/api/reviews/${reviewId}/decision`,{decision:'approve',reason:'Reviewed submitted negative annotation',revision_ids:[revision]});expect(approval.status).toBe(200);expect(approval.json.revision_ids).toEqual([revision]);
  const viewer=await addUser(admin,app.base_url,projectId,'viewer');const denied=await viewer.client.request<Json>('POST',`/api/reviews/${reviewId}/decision`,{decision:'approve',reason:'not allowed',revision_ids:[revision]});expect(denied.status).toBe(403);
  const createdIssue=await reviewer.client.request<Json>('POST',`/api/reviews/${reviewId}/issues`,{annotation_revision_id:revision,object_id:null,code:'verify-negative',message:'Confirmed empty annotation was reviewed',region:null});expect(createdIssue.status).toBe(200);
  const nextOntology=await admin.request<Json>('POST',`/api/projects/${projectId}/ontologies`,{...ontology,guidelines_markdown:'T26 revised ontology'});expect(nextOntology.status).toBe(201);
  const laterTask=await admin.request<Json>('POST',`/api/projects/${projectId}/tasks`,{asset_revision_id:asset,ontology_version_id:ontologyId,assignee_id:newAnnotator.userId});expect(laterTask.status).toBe(200);const laterTaskId=str(laterTask.json,'task_id');const laterLease=await newAnnotator.client.request<Json>('POST',`/api/tasks/${laterTaskId}/lease`,{action:'acquire'});expect(laterLease.status).toBe(200);
  const changedObject={object_id:`t26-object-${crypto.randomUUID()}`,label_id:'label_person',geometry:{type:'bbox_xyxy',x_min:10,y_min:10,x_max:30,y_max:30},attributes:{},origin:{type:'manual',prediction_id:null,model_run_id:null,import_batch_id:null}};
  const laterSave=await newAnnotator.client.request<Json>('PUT',`/api/assets/${asset}/annotation`,{operation_id:crypto.randomUUID(),base_revision_id:revision,document:{...document,completion:'complete',objects:[changedObject]},lease:{task_id:laterTaskId,fencing_token:laterLease.json.fencing_token},suggestion_decisions:[]});expect(laterSave.status).toBe(200);const laterRevision=str(laterSave.json.revision,'annotation_revision_id');expect(laterRevision).not.toBe(revision);
  const positiveSubmission=await newAnnotator.client.request<Json>('POST',`/api/tasks/${laterTaskId}/submit`,{annotation_revision_ids:[laterRevision]});expect(positiveSubmission.status).toBe(200);const positiveReviewId=str(positiveSubmission.json,'review_id');
  expect((await reviewer.client.request<Json>('POST',`/api/reviews/${positiveReviewId}/decision`,{decision:'reject',reason:'Object needs another pass',revision_ids:[laterRevision]})).status).toBe(200);
  const objectIssue=await reviewer.client.request<Json>('POST',`/api/reviews/${positiveReviewId}/issues`,{annotation_revision_id:laterRevision,object_id:changedObject.object_id,code:'object-check',message:'Check this specific object',region:changedObject.geometry});expect(objectIssue.status).toBe(200);
  const deleteObjectSave=await newAnnotator.client.request<Json>('PUT',`/api/assets/${asset}/annotation`,{operation_id:crypto.randomUUID(),base_revision_id:laterRevision,document:{...document,completion:'confirmed_negative',objects:[]},lease:{task_id:laterTaskId,fencing_token:laterLease.json.fencing_token},suggestion_decisions:[]});expect(deleteObjectSave.status).toBe(200);const laterUnreviewedRevision=str(deleteObjectSave.json.revision,'annotation_revision_id');expect(laterUnreviewedRevision).not.toBe(laterRevision);
  const resubmission=await newAnnotator.client.request<Json>('POST',`/api/tasks/${laterTaskId}/submit`,{annotation_revision_ids:[laterUnreviewedRevision]});expect(resubmission.status).toBe(200);const resubmittedReviewId=str(resubmission.json,'review_id');expect(resubmittedReviewId).not.toBe(positiveReviewId);expect(resubmission.json.revision_ids).toEqual([laterUnreviewedRevision]);
  const oldDecision=await reviewer.client.request<Json>('POST',`/api/reviews/${positiveReviewId}/decision`,{decision:'reject',reason:'Object needs another pass',revision_ids:[laterRevision]});expect(oldDecision.status).toBe(409);expect(oldDecision.json.code).toBe('REVIEW_ALREADY_DECIDED');
  const objectIssueHistory=await reviewer.client.request<Json>('GET',`/api/reviews/${positiveReviewId}/issues`);expect(objectIssueHistory.status).toBe(200);expect(objectIssueHistory.json.items[0].annotation_revision_id).toBe(laterRevision);expect(objectIssueHistory.json.items[0].object_id).toBe(changedObject.object_id);
  const oldHistory=await reviewer.client.request<Json>('GET',`/api/annotation-revisions/${revision}`);expect(oldHistory.status).toBe(200);expect(oldHistory.json.annotation_revision_id).toBe(revision);
  const issueHistory=await reviewer.client.request<Json>('GET',`/api/reviews/${reviewId}/issues`);expect(issueHistory.status).toBe(200);expect(issueHistory.json.items[0].annotation_revision_id).toBe(revision);expect(issueHistory.json.items[0].ontology_version_id).toBe(ontologyId);
  const listed=await reviewer.client.request<Json>('GET',`/api/projects/${projectId}/tasks`);expect(listed.status).toBe(200);const rows=listed.json.items as Json[];expect(rows.find(x=>x.task_id===taskId)?.review_id).toBe(reviewId);expect(rows.find(x=>x.task_id===taskId)?.review_decision).toBe('approve');expect(rows.find(x=>x.task_id===laterTaskId)?.review_id).toBe(resubmittedReviewId);expect(rows.find(x=>x.task_id===laterTaskId)?.review_decision).toBeNull();expect(rows.find(x=>x.task_id===laterTaskId)?.state).toBe('submitted');expect(rows.find(x=>x.task_id===laterTaskId)?.revision_ids).toEqual([laterUnreviewedRevision]);
 } finally {await app.stop();}
});
