import { spawnSync } from 'node:child_process';
import { appendFileSync, mkdirSync } from 'node:fs';
import { resolve } from 'node:path';
import { resolveArgv } from '../../scripts/task.mjs';
const root = resolve(import.meta.dirname, '../..');
const [label, command, ...args] = process.argv.slice(2);
if (!label || !command) throw new Error('usage: run-command.mjs LABEL COMMAND ARGS...');
const cargo = command === 'cargo';
const env = { ...process.env, RUSTUP_TOOLCHAIN: '1.96.0', RUSTC: 'D:/cache/cargo/toolchains/1.96.0-x86_64-pc-windows-msvc/bin/rustc.exe' };
const temporary = resolve(root, 'target/t34-tmp');
mkdirSync(temporary, { recursive: true });
env.TMP = env.TEMP = temporary;
if (!cargo) env.WEBLABEL_API_BINARY = resolve(root, 'target/debug/weblabel-api.exe');
const [actual, ...actualArgs] = resolveArgv([command, ...args]);
const result = spawnSync(actual, actualArgs, { cwd: cargo ? 'D:/cache/cargo/bin' : root, env, encoding: 'utf8', shell: false, maxBuffer: 32 * 1024 * 1024 });
const output = `${result.stdout ?? ''}${result.stderr ?? ''}${result.error ? String(result.error) : ''}`;
const cwd = cargo ? 'D:/cache/cargo/bin' : root;
const counts = [...output.matchAll(/(?:Tests\s+|test result: ok\. )(\d+) passed(?: \| (\d+) failed)?(?: \| (\d+) skipped)?/g)].map((match) => ({ passed: Number(match[1]), failed: Number(match[2] ?? 0), skipped: Number(match[3] ?? 0) }));
const playwright = output.match(/(?:^|\n)\s*(\d+) passed \([\d.]+s\)/);
if (playwright) counts.push({ passed: Number(playwright[1]), failed: 0, skipped: 0 });
const evidence = { label, requested_argv: [command, ...args], actual_argv: [actual, ...actualArgs], cwd, exit_code: result.status, test_counts: counts, environment: { RUSTUP_TOOLCHAIN: env.RUSTUP_TOOLCHAIN, RUSTC: env.RUSTC, WEBLABEL_API_BINARY: env.WEBLABEL_API_BINARY ?? null, TMP: temporary, TEMP: temporary } };
appendFileSync(resolve(root, 'reports/T34/commands.jsonl'), `${JSON.stringify(evidence)}\n`);
appendFileSync(resolve(root, 'reports/T34/tests.log'), `\n## ${label}\nargv=${JSON.stringify([command,...args])}\nactual_argv=${JSON.stringify([actual,...actualArgs])}\ncwd=${cwd}\nexit_code=${result.status}\n${output}\n`);
process.stdout.write(output);
process.exit(result.status ?? 1);
